# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.13.105"
  config.vm.hostname = "magento"

  config.vm.provider "virtualbox" do |v|
    v.name = "magento"
  end

  config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/opt/fyndiq-magento-module"

  config.vm.provision :shell, path: "./provision1.9.2.0.sh"
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end
