<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = '<?php echo $this->getAdminPath("fyndiq/service"); ?>';
    shared_path = '<?php echo $this->getFrontendPath(); ?>';
    var urlpath0 = '<?php echo str_replace('index.php/','',Mage::getBaseUrl()); ?>';
</script>
<style type="text/css">
    a i.menu-icon.comp {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/comp_red.png');
    }
    a.active i.menu-icon.comp,a:hover i.menu-icon.comp {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/comp_white.png');
    }
    a i.menu-icon.boxes {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/box_red.png');
    }
    a.active i.menu-icon.boxes,a:hover i.menu-icon.boxes {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/box_white.png');
    }
    a i.menu-icon.cog {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cog_red.png');
    }
    a.active i.menu-icon.cog,a:hover i.menu-icon.cog {
        background-position: 0px -1px;
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cog_white.png');
    }
</style>

<?php require(Mage::getBaseDir('code').'/community/Fyndiq/Fyndiq/includes/shared/frontend/templates/js_templates_without_smarty.tpl'); ?>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {
    ?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <?php
    }
    ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
