<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = "<?php echo $this->getAdminPath("fyndiq/service"); ?>";
    frontend_path = "<?php echo $this->getFrontendPath(); ?>frontend/";
</script>
<style type="text/css">
    a i.menu-icon.comp {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/comp_red.png');
    }
    a.active i.menu-icon.comp,a:hover i.menu-icon.comp {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/comp_white.png');
    }
    a i.menu-icon.boxes {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/box_red.png');
    }
    a.active i.menu-icon.boxes,a:hover i.menu-icon.boxes {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/box_white.png');
    }
    a i.menu-icon.cog {
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cog_red.png');
    }
    a.active i.menu-icon.cog,a:hover i.menu-icon.cog {
        background-position: 0px -1px;
        background-image: url('<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cog_white.png');
    }
</style>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close"
             title="Close message">

        <h3>{{title}}</h3>

        <p>{{message}}</p>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-modal-overlay">
    <div class="fm-modal-overlay">
        <div class="container">
            <div class="content"></div>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-price-warning-controls">
    <div class="controls">
        <button class="fm-button cancel" name="cancel" data-modal-type="cancel">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cancel.png">
            Cancel
        </button>
        <button class="fm-button accept" name="accept" data-modal-type="accept">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/accept.png">
            Accept
        </button>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-accept-product-export">
    <div class="fm-accept-product-export">
        <h3>Warning!</h3>

        <p>
            Check once again that the percentage and data about the product is correct. Here is the product you have
            selected for export. Already exported product will get its stock and price overwritten.
        </p>

        {{> fm-product-price-warning-controls}}

        <ul>
            {{#each product_warnings}}
            <li>
                <div class="image">
                    {{#with product}}{{#with product}}
                    {{#if image}}
                    <img src="{{image}}" alt="Product image">
                    {{/if}}
                    {{/with}}{{/with}}
                </div>

                <div class="data">
                    <div class="title">
                        {{#with product}}{{#with product}}
                        <input type="text" value="{{name}}">
                        {{/with}}{{/with}}
                    </div>

                    <div class="price-info">
                        {{#with product}}{{#with product}}
                        <div class="highest-price">
                            Your Price: {{price}}
                        </div>

                        <div class="lowest-price">
                            Fyndiq Discount: {{fyndiq_precentage}}%
                        </div>

                    </div>
                </div>
                <div class="description-showbutton">
                    <button>Show Description</button>
                </div>
                <div class="final-price">
                    <label>Discount precentage:</label>
                    <input type="text" value="{{fyndiq_precentage}}">
                </div>
                <div class="description-container"><textarea class="description">{{description}}</textarea></div>
                {{/with}}{{/with}}
            </li>
            {{/each}}
        </ul>

        {{> fm-product-price-warning-controls}}
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-category-tree">
    <ul class="fm-category-tree">
        {{#each categories}}
        {{#with this}}
        <li data-category_id="{{id}}">
            {{level}}

            <a href="#" title="Open category">{{name}}</a>
        </li>
        {{/with}}
        {{/each}}
    </ul>
</script>
<script type="text/x-handlebars-template" class="handlebars-template" id="fm-category-child-tree">
    <ul class="fm-category-tree childtree" style="padding-left:10px;">
        {{#each categories}}
        {{#with this}}
        <li data-category_id="{{id}}">
            {{level}}

            <a href="#" title="Open category">{{name}}</a>
        </li>
        {{/with}}
        {{/each}}
    </ul>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-pagination">
    {{#if pagination}}
    <div class="pages">
        {{{pagination}}}
    </div>
    {{/if}}
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-list-controls">
    <div class="fm-product-list-controls">
        <div class="export">
            <a class="fm-button disabled" id="delete-products">Remove from Fyndiq</a>
            <a class="fm-button green" id="export-products">Send to Fyndiq</a>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-product-list">
    {{> fm-product-list-controls}}
    <div class="fm-products-list-container">
        {{#if products}}
        <table>
            <thead>
            <tr>
                <th><input id="select-all" type="checkbox"></th>
                <th colspan="2">Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody class="fm-product-list">
            {{#each products}}
            {{#with this}}
            <tr
                data-id="{{id}}"
                data-name="{{name}}"
                data-reference="{{reference}}"
                data-description="{{description}}"
                data-price="{{price}}"
                data-quantity="{{quantity}}"
                {{#if image}}
                data-image="{{image}}"
                {{else}}
                data-image="false"
                {{/if}}
                class="product">
                {{#if image}}
                <td class="select center"><input type="checkbox" id="select_product_{{id}}"></td>
                <td><img src="{{image}}" alt="Product image"></td>
                {{else}}
                <td class="select center"></td>
                <td>No Image</td>
                {{/if}}
                <td><strong>{{name}}</strong> <span class="shadow">({{reference}})</span><br/>{{properties}}</td>
                <td class="prices">
                    <div class="price">
                        Price: <span class="pricetag">{{price}} <?php echo $this->getCurrency(); ?></span>
                </div>
                    <div class="fyndiq_price">
                        <label>Fyndiq Discount:</label>
                        <div class="inputdiv"><input type="text" value="{{fyndiq_price}}" class="fyndiq_dicsount">%</div><span
                        id="ajaxFired"></span><br />
                        <span>Expected Price: </span><span class="price_preview"><span class="price_preview_price">{{expected_price}}</span> <?php echo $this->getCurrency(); ?></span>
                </div>
                </td>
                <td class="quantities center">
                    {{quantity}}
                </td>
                <td class="status center">
                    {{#if fyndiq_exported}}
                    <i class="icon on big"></i>
                    {{else}}
                    <i class="icon noton big"></i>
                    {{/if}}
                </td>
            </tr>
            {{/with}}
            {{/each}}
            </tbody>
        </table>
        {{else}}
        <span class="notext">Category is empty.</span>
        {{/if}}
    </div>
    {{> fm-product-list-controls}}
    {{> fm-product-pagination}}
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {
    ?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <?php
    }
    ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/main.js"></script>

<div class="fm-header">
    <div class="fm-header-wrapper">
        <img class="navbar-brand" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
        <div class="navbar-right">
            <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav active"><i class="menu-icon comp"></i> Export Products</a>
            <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav"><i class="menu-icon boxes"></i> Imported Orders</a>
            <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>" class="btn btn-nav"><i class="menu-icon cog"></i> Settings</a>
        </div>
    </div>
</div>
<div class="fm-container">

    <div class="fm-content-wrapper">
        <div class="fm-left-sidebar">
            <div class="fm-panel">
            <div class="fm-panel-header">Categories</div>
            <div class="fm-panel-body fm-category-tree-container no-padding"></div>
            </div>
        </div>

        <div class="fm-product-panel">
            <div class="fm-panel">
                <div class="fm-panel-header">
                    Products: <span id="categoryname"></span>
                    <div class="legend"><i class="icon on"></i> On Fyndiq  <i class="icon pending"></i> Pending <i class="icon noton"></i> Not On Fyndiq </div>
                </div>
                <div class="fm-panel-body no-padding">
                    <form action="" method="post" class="fm-form products">
                            <p class="info">By using this form, you can export products from the local webshop into Fyndiq.</p>
                            <div class="fm-product-list-container"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br class="clear" />
</div>