<?php require('common.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/main.js"></script>

<div class="fm-container">

    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
            <div class="navbar-right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav active"><i class="menu-icon comp"></i> Export Products</a>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav"><i class="menu-icon boxes"></i> Imported Orders</a>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>" class="btn btn-nav"><i class="menu-icon cog"></i> Settings</a>
            </div>
        </div>
    </div>

    <div class="fm-content-wrapper">
        <div class="fm-left-sidebar">
            <div class="fm-panel">
            <div class="fm-panel-header">Categories</div>
            <div class="fm-panel-body fm-category-tree-container no-padding"></div>
            </div>
        </div>

        <div class="fm-product-panel">
            <div class="fm-panel">
                <div class="fm-panel-header">
                    Products: <span id="categoryname"></span>
                    <div class="legend"><i class="icon on"></i> On Fyndiq  <i class="icon pending"></i> Pending <i class="icon noton"></i> Not On Fyndiq </div>
                </div>
                <div class="fm-panel-body no-padding">
                    <form action="" method="post" class="fm-form products">
                            <p class="info">By using this form, you can export products from the local webshop into Fyndiq.</p>
                            <div class="fm-product-list-container"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br class="clear" />
</div>