<?php require('common.phtml'); ?>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/orderlist.js"></script>

<div class="fm-container">

    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
            <div class="navbar-right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav"><i class="menu-icon comp"></i> Export Products</a>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav active"><i class="menu-icon boxes"></i> Imported Orders</a>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>" class="btn btn-nav"><i class="menu-icon cog"></i> Settings</a>
            </div>
        </div>
    </div>


    <div class="fm-content-wrapper">
        <div class="fm-orderlist-panel">
            <div class="fm-panel">
                <div class="fm-panel-header">Imported Orders</div>
                <div class="fm-panel-body no-padding">
                    <form action="<?php echo $this->getAdminPath("fyndiq/service"); ?>" method="post" class="fm-form orders-form">
                        <input type="hidden" name="action" value="get_delivery_notes" />
                        <div class="fm-order-list-container"></div>
                    </form>
                </div>
            </div>
        </div>

        <div class="fm-sidebar">
            <div class="fm-panel">
                <div class="fm-panel-header">Manual Order Import</div>
                <div class="fm-panel-body">
                    <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                    <div id="fm-order-import-date">
                        <?php
                            $currentdate = $this->getLastUpdatedDate();
                            if ($currentdate != false) {
                        ?>
                        <div class="lastupdated">
                            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/refresh.png" />
                            <span class="last-header">Latest Import</span>
                            <?php
                                $current = strtotime(date("Y-m-d"));
                                $date    = strtotime(date("Y-m-d",strtotime($currentdate)));

                                $datediff = $date - $current;
                                $differance = floor($datediff/(60*60*24));
                                if($differance==0) {
                                    echo 'Today <span class="shadow">('.date ("G:i:s", strtotime($currentdate)) . ')</span>';
                                } else {
                                    echo date ("Y-m-d G:i:s", strtotime($currentdate));
                                }
                            ?>
                        </div>
                        <?php
                            }
                        ?>
                    <a class="fm-button green" id="fm-import-orders">Import Orders</a>
                </div>
            </div>
        </div>
    </div>
    <br class="clear" />
</div>
