<?php require('common.phtml'); ?>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close"
             title="Close message">

        <h3>{{title}}</h3>

        <p>{{{message}}}</p>
    </div>
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-order-pagination">
    {{#if pagination}}
    <div class="pages">
        {{{pagination}}}
    </div>
    {{/if}}
</script>
<script type="text/x-handlebars-template" class="handlebars-template" id="fm-orders-list">
    {{> fm-order-list-controls}}
    {{#if orders}}
    <table>
        <thead>
        <tr>
            <th><input id="select-all" type="checkbox"></th>
            <th colspan="1">Order</th>
            <th>Fyndiq Order</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Status</th>
            <th>Created</th>
        </tr>
        </thead>
        <tbody class="fm-orders-list">
        {{#each orders}}
        {{#with this}}
        <tr data-id="{{order_id}}" data-fyndiqid="{{fyndiq_orderid}}">
            <td class="select center"><input type="checkbox" value="{{fyndiq_orderid}}" name="args[orders][]" id="select_order_{{entity_id}}"></td>
            <td class="center">{{order_id}}</td>
            <td class="center">{{fyndiq_orderid}}</td>
            <td class="center">{{price}}</td>
            <td class="center">{{total_products}}</td>
            <td class="center">{{state}}</td>
            <td class="center">{{created_at}} <span class="shadow">({{created_at_time}})</span></td>
        </tr>
        {{/with}}
        {{/each}}
        </tbody>
    </table>
    {{else}}
    Orders is empty.
    {{/if}}
    {{> fm-order-pagination}}
    {{> fm-order-list-controls}}
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-order-list-controls">
    <div class="fm-order-list-controls">
        <div class="export">
            <a class="fm-button green" id="getdeliverynote">Get Delivery Notes</a>
        </div>
    </div>
</script>



<div class="fm-container">

    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
            <div class="navbar-right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav"><i class="menu-icon comp"></i> Export Products</a>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav active"><i class="menu-icon boxes"></i> Imported Orders</a>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>" class="btn btn-nav"><i class="menu-icon cog"></i> Settings</a>
            </div>
        </div>
    </div>


    <div class="fm-content-wrapper">
        <div class="fm-orderlist-panel">
            <div class="fm-panel">
                <div class="fm-panel-header">Imported Orders</div>
                <div class="fm-panel-body no-padding">
                    <form action="<?php echo $this->getAdminPath("fyndiq/service"); ?>" method="post" class="fm-form orders-form">
                        <input type="hidden" name="action" value="get_delivery_notes" />
                        <div class="fm-order-list-container"></div>
                    </form>
                </div>
            </div>
        </div>

        <div class="fm-sidebar">
            <div class="fm-panel">
                <div class="fm-panel-header">Manual Order Import</div>
                <div class="fm-panel-body">
                    <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                    <div id="fm-order-import-date">
                        <?php
                            $currentdate = $this->getLastUpdatedDate();
                            if ($currentdate != false) {
                        ?>
                        <div class="lastupdated">
                            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/refresh.png" />
                            <span class="last-header">Latest Import</span>
                            <?php
                                $current = strtotime(date("Y-m-d"));
                                $date    = strtotime(date("Y-m-d",strtotime($currentdate)));

                                $datediff = $date - $current;
                                $differance = floor($datediff/(60*60*24));
                                if($differance==0) {
                                    echo 'Today <span class="shadow">('.date ("G:i:s", strtotime($currentdate)) . ')</span>';
                                } else {
                                    echo date ("Y-m-d G:i:s", strtotime($currentdate));
                                }
                            ?>
                        </div>
                        <?php
                            }
                        ?>
                    <a class="fm-button green" id="fm-import-orders">Import Orders</a>
                </div>
            </div>
        </div>
    </div>
    <br class="clear" />
</div>
