<?php require('common.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->getSharedPath(); ?>frontend/js/main.js"></script>

<div class="fm-container">

    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png"
                 alt="<?php echo $this->getMessage('Fyndiq logotype'); ?>">

            <div class="navbar-right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="btn btn-nav active"><i
                        class="menu-icon comp"></i> <?php echo $this->getMessage('Export Products'); ?></a>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="btn btn-nav"><i
                        class="menu-icon boxes"></i> <?php echo $this->getMessage('Imported Orders'); ?></a>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>"
                   class="btn btn-nav"><i class="menu-icon cog"></i> <?php echo $this->getMessage('Settings'); ?></a>
            </div>
        </div>
    </div>

    <div class="fm-content-wrapper">
        <div class="fm-left-sidebar">
            <div class="fm-panel">
                <div class="fm-panel-header"><?php echo $this->getMessage('Categories'); ?></div>
                <div class="fm-panel-body no-padding">
                    <ul class="fm-category-tree">
                        <li data-category_id="-1">
                            <a href="#" title="<?php echo $this->getMessage('All products'); ?>"><?php echo $this->getMessage('All products'); ?></a>
                        </li>
                    </ul>
                    <div class="fm-category-tree-container"></div>
                </div>
            </div>
        </div>

        <div class="fm-product-panel">
            <div class="fm-panel">
                <div class="fm-panel-header">
                    <?php echo $this->getMessage('Products'); ?>: <span id="categoryname"></span>

                    <div class="legend">
                        <i class="icon on"></i> <?php echo $this->getMessage('On Fyndiq'); ?>
                        <i class="icon pending"></i> <?php echo $this->getMessage('Pending'); ?>
                        <i class="icon noton"></i> <?php echo $this->getMessage('Not On Fyndiq'); ?>
                    </div>
                </div>
                <div class="fm-panel-body no-padding">
                    <form action="" method="post" class="fm-form products">
                        <p class="info"><?php echo $this->getMessage(
                                'By using this form, you can export products from the local webshop into Fyndiq.'
                            ); ?></p>

                        <div class="fm-product-list-container"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br class="clear" />
</div>
