<link rel="stylesheet" type="text/css" href="<?php echo $this->getModulePath(); ?>frontend/css/main.css" media="all">

<?php //include($this->getModulePath().'/frontend/templates/js_templates.tpl'); ?>

<script type="text/javascript" src="<?php echo $this->getModulePath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var module_path = '{$module_path}';
    var messages = {};
    {
        foreach
        $messages
        as
        $k =
    >
        $v
    }
    messages['{$k}'] = '{$v}';
    {/foreach
    }
</script>

<script type="text/javascript" src="<?php echo $this->getModulePath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getModulePath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getModulePath(); ?>frontend/js/main.js"></script>


<div class="fm-container">

    <img class="fyndiqlogo" src="<?php echo $this->getModulePath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">

    <div class="fm-main-panel">

        {* Product list form *}
        <form action="" method="post" class="fm-form products">
            <fieldset>
                <legend>Products</legend>
                <p>By using this form, you can export products from the local webshop into Fyndiq.</p>

                <div class="fm-category-tree-container"></div>
                <div class="fm-product-list-container"></div>
            </fieldset>
        </form>
    </div>

    <div class="fm-sidebar">

        <h3>Import orders</h3>

        <form action="" method="post" class="fm-form orders">
            <fieldset>
                <legend>Orders</legend>
                <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                <button class="fm-button fyndiq" name="import-orders">Import Orders</button>
            </fieldset>
        </form>

        <h3>Settings</h3>

        <form action="" method="post" class="fm-form settings">
            <fieldset>
                <legend>Settings</legend>
                <p>
                <ul>
                    <li>
                        Language: <b><?php echo $this->getLanguage(); ?></b>
                    </li>

                    <li>
                        Currency: <b><?php echo $this->getCurrency(); ?></b>
                    </li>

                    <li>
                        Automatic order import: <b><?php if ($this->getAutoOrderImport()) {
                                echo "Enabled";
                            } else {
                                echo "Disabled";
                            } ?></b>
                    </li>

                    <li>
                        Automatic quantity export: <b><?php if ($this->getAutoProductExport()) {
                                echo "Enabled";
                            } else {
                                echo "Disabled";
                            } ?></b>
                    </li>
                </ul>
                </p>

                <a class="fm-button" type="submit" name="submit_show_settings"
                   href="admin/system_config/edit/section/fyndiq">Change Settings</a>
            </fieldset>
        </form>

        <h3>Disconnect account</h3>

        <form action="" method="post" class="fm-form disconnect">
            <fieldset>
                <legend>Account</legend>
                <p>Current user: <b><?php echo $this->getUsername(); ?></b></p>

                <p>By clicking this button, you can disconnect from your Fyndiq merchant account.</p>
                <button class="fm-button" type="submit" name="submit_disconnect"
                        onclick="return confirm('{FmMessages::get('disconnect-confirm')}');"
                    >Disconnect Account
                </button>
            </fieldset>
        </form>
    </div>
</div>
