<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = "<?php echo $this->getAdminPath("fyndiq/service"); ?>";
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close" title="Close message">
        <h3>{{title}}</h3>
        <p>{{message}}</p>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-modal-overlay">
    <div class="fm-modal-overlay">
        <div class="container">
            <div class="content"></div>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-price-warning-controls">
    <div class="controls">
        <button class="fm-button cancel" name="cancel" data-modal-type="cancel">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cancel.png">
            Cancel
        </button>
        <button class="fm-button accept" name="accept" data-modal-type="accept">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/accept.png">
            Accept
        </button>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-accept-product-export">
    <div class="fm-accept-product-export">
        <h3>Warning!</h3>
        <p>
            Check once again that the price for Fyndiq is correct and as you want it. We show the two different prices and let you choose what you feel best suited for the product.
        </p>

        {{> fm-product-price-warning-controls}}

        <ul>
            {{#each product_warnings}}
            <li>
                <div class="image">
                    {{#with product}}{{#with product}}
                    {{#if image}}
                    <img src="{{image}}" alt="Product image">
                    {{/if}}
                    {{/with}}{{/with}}
                </div>

                <div class="data">
                    <div class="title">
                        {{#with product}}{{#with product}}
                        <input type="text" value="{{name}}">
                            {{/with}}{{/with}}
                    </div>

                    <div class="price-info">
                        {{#with product}}{{#with product}}
                        <div class="highest-price">
                            Your Price: {{price}}
                        </div>

                        <div class="lowest-price">
                            Fyndiq Price: {{fyndiq_price}}
                        </div>

                    </div>
                </div>
                <div class="final-price">
                    <label>Price:</label>
                    {{#with product}}{{#with product}}
                    <input type="text" value="{{fyndiq_price}}">
                    {{/with}}{{/with}}
                </div>
                {{/with}}{{/with}}
            </li>
            {{/each}}
        </ul>

        {{> fm-product-price-warning-controls}}
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-category-tree">
    <ul class="fm-category-tree">
        {{#each categories}}
        {{#with this}}
        <li data-category_id="{{id}}">
            {{level}}

            <a href="#" title="Open category">{{name}}</a>
        </li>
        {{/with}}
        {{/each}}
    </ul>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-list-controls">
    <div class="fm-product-list-controls">
        <div class="select">
            <button class="fm-button" name="select-all">Select All</button>
            <button class="fm-button" name="deselect-all">Deselect All</button>
        </div>
        <div class="export">
            <button class="fm-button fyndiq" name="export-products">Export Products</button>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-product-list">
    {{> fm-product-list-controls}}
    {{#if products}}
    <table>
        <thead>
        <tr>
            <th colspan="3">Product</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tbody class="fm-product-list">
        {{#each products}}
        {{#with this}}
        <tr
            data-id="{{id}}"
            data-name="{{name}}"
            data-reference="{{reference}}"
            data-price="{{price}}"
            data-quantity="{{quantity}}"
            data-image="{{image}}"
            >
            <td class="select"><input type="checkbox" id="select_product_{{id}}"></td>
            <td><img src="{{image}}" alt="Product image"></td>
            <td>{{name}} ({{reference}})</td>
            <td class="prices">
                <div class="price">
                    <label>Price:</label>
                    <input type="text" value="{{price}}">
                </div>
                <div class="fyndiq_price">
                    <label>Fyndiq Price:</label>
                    <input type="text" value="{{fyndiq_price}}">
                </div>
            </td>
            <td><div class="quantities">
                <div>Qty: {{quantity}}</div>
                <div>Exported Qty: 6</div>
                <div>Fyndiq Qty: 4</div>
            </div></td>
            </tr>
        {{/with}}
        {{/each}}
    </tbody>
    </table>
    {{else}}
    Category is empty.
    {{/if}}
    {{> fm-product-list-controls}}
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <? } ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/main.js"></script>


<div class="fm-container">

    <img class="fyndiqlogo" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">

    <div class="fm-main-panel">

        <h2>Products</h2>
        <form action="" method="post" class="fm-form products">
            <fieldset>
                <legend>Products</legend>
                <p>By using this form, you can export products from the local webshop into Fyndiq.</p>

                <div class="fm-category-tree-container"></div>
                <div class="fm-product-list-container"></div>
            </fieldset>
        </form>
    </div>

    <div class="fm-sidebar">

        <h3>Import orders</h3>

        <form action="" method="post" class="fm-form orders">
            <fieldset>
                <legend>Orders</legend>
                <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                <button class="fm-button fyndiq" name="import-orders">Import Orders</button>
            </fieldset>
        </form>

        <h3>Settings</h3>

        <form action="" method="post" class="fm-form settings">
            <fieldset>
                <legend>Settings</legend>
                <p>
                <ul>
                    <li>
                        Language: <b><?php echo $this->getLanguage(); ?></b>
                    </li>

                    <li>
                        Currency: <b><?php echo $this->getCurrency(); ?></b>
                    </li>

                    <li>
                        Automatic order import: <b><?php if ($this->getAutoOrderImport()) {
                                echo "Enabled";
                            } else {
                                echo "Disabled";
                            } ?></b>
                    </li>

                    <li>
                        Automatic quantity export: <b><?php if ($this->getAutoQuantityExport()) {
                                echo "Enabled";
                            } else {
                                echo "Disabled";
                            } ?></b>
                    </li>
                </ul>
                </p>

                <a class="fm-button" type="submit" name="submit_show_settings"
                   href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Change Settings</a>
            </fieldset>
        </form>

        <h3>Disconnect account</h3>

        <form action="" method="post" class="fm-form disconnect">
            <fieldset>
                <legend>Account</legend>
                <p>Current user: <b><?php echo $this->getUsername(); ?></b></p>

                <p>By clicking this button, you can disconnect from your Fyndiq merchant account.</p>
                <button class="fm-button" type="submit" name="submit_disconnect"
                        onclick="return confirm('<?php echo $this->getMessage('disconnect-confirm'); ?>');"
                    >Disconnect Account
                </button>
            </fieldset>
        </form>
    </div>
</div>
