<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = "<?php echo $this->getAdminPath("fyndiq/service"); ?>";
    var urlpath0 = "<?php echo str_replace('index.php/','',Mage::getBaseUrl()); ?>";
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close"
             title="Close message">

        <h3>{{title}}</h3>

        <p>{{{message}}}</p>
    </div>
</script>
<script type="text/x-handlebars-template" class="handlebars-template" id="fm-orders-list">
    {{> fm-order-list-controls}}
    {{#if orders}}
    <table>
        <thead>
        <tr>
            <th><input id="select-all" type="checkbox"></th>
            <th colspan="1">Order</th>
            <th>Fyndiq Order</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Created</th>
        </tr>
        </thead>
        <tbody class="fm-orders-list">
        {{#each orders}}
        {{#with this}}
        <tr data-id="{{entity_id}}" data-fyndiqid="{{fyndiq_order}}">
            <td class="select center"><input type="checkbox" id="select_order_{{entity_id}}"></td>
            <td class="center">{{entity_id}}</td>
            <td class="center">{{fyndiq_order}}</td>
            <td class="center">{{base_grand_total}} <?php echo $this->getCurrency(); ?></td>
            <td class="center">{{total_qty_ordered}}</td>
            <td class="center">{{created_at}}</td>
        </tr>
        {{/with}}
        {{/each}}
        </tbody>
    </table>
    {{else}}
    Orders is empty.
    {{/if}}
    {{> fm-order-list-controls}}
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-order-list-controls">
    <div class="fm-order-list-controls">
        <div class="export">
            <a class="fm-button green" id="getdeliverynote">Get Delivery Notes</a>
        </div>
    </div>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {
    ?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <?php
    }
    ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/orderlist.js"></script>


<div class="fm-header-background">
    <div class="fm-header-container">
        <div class="fm-header">
            <img class="fyndiqlogo" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
            <div class="right">
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>">Export Products</a>
                <a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="active">Imported Orders</a>
                <a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Settings</a>
            </div>
        </div>
    </div>
</div>
<div class="fm-container">

    <div class="fm-orderlist-panel">
        <div class="fm-subheader">Import Orders</div>

        <form action="" method="post" class="fm-form orders-form">

            <div class="fm-order-list-container"></div>
        </form>
    </div>

    <div class="fm-sidebar">
        <div class="fm-subheader">Manual Order Import</div>
        <div class="content">
                <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                <?php
                $date = $this->getLastUpdatedDate();
                if ($date != false) {
                    ?><br/>Last Updated: <?php echo $date;
                }
                ?>
                <a class="fm-button green block" id="fm-import-orders">Import Orders</a>
        </div>
    </div>
</div>