<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = "<?php echo $this->getAdminPath("fyndiq/service"); ?>";
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close" title="Close message">
        <h3>{{title}}</h3>
        <p>{{{message}}}</p>
    </div>
</script>
<script type="text/x-handlebars-template" class="handlebars-template" id="fm-orders-list">
    {{> fm-order-list-controls}}
    {{#if orders}}
    <table>
        <thead>
        <tr>
            <th><input id="select-all" type="checkbox"></th>
            <th colspan="1">Order</th>
            <th>Fyndiq Order</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Created</th>
        </tr>
        </thead>
        <tbody class="fm-orders-list">
        {{#each orders}}
        {{#with this}}
        <tr data-id="{{entity_id}}">
            <td class="select"><input type="checkbox" id="select_product_{{entity_id}}"></td>
            <td>{{entity_id}}</td>
            <td>{{fyndiq_order}}</td>
            <td>{{base_grand_total}}</td>
            <td>{{total_qty_ordered}}</td>
            <td>{{created_at}}</td>
        </tr>
        {{/with}}
        {{/each}}
        </tbody>
    </table>
    {{else}}
    Orders is empty.
    {{/if}}
    {{> fm-order-list-controls}}
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-order-list-controls">
    <div class="fm-order-list-controls">
        <div class="export">
            <button class="fm-button fyndiq" id="getdeliverynote">Get Delivery Notes</button>
        </div>
    </div>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <? } ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/orderlist.js"></script>


<div class="fm-container">

    <img class="fyndiqlogo" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">

    <div class="fm-menu">
        <ul>
            <li><a href="<?php echo $this->getAdminPath("fyndiq/admin/exportproducts"); ?>">Export products</a></li>
            <li><a href="#">Exported products</a></li>
            <li><a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>" class="active">Imported Orders</a></li>
            <li><a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Settings</a></li>
        </ul>
        <ul class="right">
            <li><a href="#" onclick="return confirm('<?php echo $this->getMessage('disconnect-confirm'); ?>');">Disconnect Account</a></li>
        </ul>
    </div>

    <div class="fm-orderlist-panel">

        <h2>Imported Orders</h2>
        <form action="" method="post" class="fm-form orders-form">

                <div class="fm-order-list-container"></div>
        </form>
    </div>

    <div class="fm-sidebar">

        <h3>Import Order</h3>

        <form action="" method="post" class="fm-form orders">
            <fieldset>
                <p>By clicking this button, you can import all orders from Fyndiq into the local webshop.</p>
                <button class="fm-button fyndiq" name="import-orders">Import Orders</button>
            </fieldset>
        </form>
    </div>
</div>