<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">

<div class="fm-container">

    <img class="fyndiqlogo" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">

    <div class="fm-main-panel">
        <form action="" method="post" class="fm-form orders">
            <fieldset>
                <h2>Wrong Currency Set</h2>
                <p>
                    We are using the default currency setting in Magento. You need to set correct currency to be able to use Fyndiq's Module.
                    <br />You can change this in Configuration (System > Configuration)
                </p>
                <p>
                    Set Currency to SEK or EUR. Also set Country to either Germany or Sweden.
                </p>
            </fieldset>
        </form>
    </div>

</div>