<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">
<script type="text/javascript">
    module_path = "<?php echo $this->getAdminPath("fyndiq/service"); ?>";
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-loading-overlay">
    <div class="fm-loading-overlay">
        <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/ajax-loader.gif" alt="Loading animation">
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-message-overlay">
    <div class="fm-message-overlay fm-{{type}}">
        <img class="close" src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/close-icon.png" alt="Close" title="Close message">
        <h3>{{title}}</h3>
        <p>{{message}}</p>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-modal-overlay">
    <div class="fm-modal-overlay">
        <div class="container">
            <div class="content"></div>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-price-warning-controls">
    <div class="controls">
        <button class="fm-button cancel" name="cancel" data-modal-type="cancel">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/cancel.png">
            Cancel
        </button>
        <button class="fm-button accept" name="accept" data-modal-type="accept">
            <img src="<?php echo $this->getFrontendPath(); ?>frontend/images/icons/accept.png">
            Accept
        </button>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-accept-product-export">
    <div class="fm-accept-product-export">
        <h3>Warning!</h3>
        <p>
            Check once again that the percentage and data about the product is correct. Here is the product you have selected for export. Already exported product will get its stock and price overwritten.
        </p>

        {{> fm-product-price-warning-controls}}

        <ul>
            {{#each product_warnings}}
            <li>
                <div class="image">
                    {{#with product}}{{#with product}}
                    {{#if image}}
                    <img src="{{image}}" alt="Product image">
                    {{/if}}
                    {{/with}}{{/with}}
                </div>

                <div class="data">
                    <div class="title">
                        {{#with product}}{{#with product}}
                        <input type="text" value="{{name}}">
                            {{/with}}{{/with}}
                    </div>

                    <div class="price-info">
                        {{#with product}}{{#with product}}
                        <div class="highest-price">
                            Your Price: {{price}}
                        </div>

                        <div class="lowest-price">
                            Fyndiq Discount: {{fyndiq_precentage}}%
                        </div>

                    </div>
                </div>
                <div class="description-showbutton">
                    <button>Show Description</button>
                </div>
                <div class="final-price">
                    <label>Discount precentage:</label>
                    <input type="text" value="{{fyndiq_precentage}}">
                </div>
                <div class="description-container"><textarea class="description">{{description}}</textarea></div>
                {{/with}}{{/with}}
            </li>
            {{/each}}
        </ul>

        {{> fm-product-price-warning-controls}}
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-category-tree">
    <ul class="fm-category-tree">
        {{#each categories}}
        {{#with this}}
        <li data-category_id="{{id}}">
            {{level}}

            <a href="#" title="Open category">{{name}}</a>
        </li>
        {{/with}}
        {{/each}}
    </ul>
</script>

<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-pagination">
    {{#if pagination}}
    <div class="pages">
        {{{pagination}}}
    </div>
    {{/if}}
</script>
<script type="text/x-handlebars-template" class="handlebars-partial" id="fm-product-list-controls">
    <div class="fm-product-list-controls">
        <div class="export">
            <button class="fm-button" name="delete-products">Remove from Fyndiq</button>
            <button class="fm-button fyndiq" name="export-products">Send to Fyndiq</button>
        </div>
    </div>
</script>

<script type="text/x-handlebars-template" class="handlebars-template" id="fm-product-list">
    {{> fm-product-list-controls}}
    <div class="fm-products-list-container">
    {{#if products}}
    <table>
        <thead>
        <tr>
            <th><input id="select-all" type="checkbox"></th>
            <th colspan="2">Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody class="fm-product-list">
        {{#each products}}
        {{#with this}}
        <tr
            data-id="{{id}}"
            data-name="{{name}}"
            data-reference="{{reference}}"
            data-description="{{description}}"
            data-price="{{price}}"
            data-quantity="{{quantity}}"
            data-image="{{image}}"
            class="product">
            <td class="select"><input type="checkbox" id="select_product_{{id}}"></td>
            <td><img src="{{image}}" alt="Product image"></td>
            <td><strong>{{name}}</strong> ({{reference}})<br/>{{properties}}</td>
            <td class="prices">
                <div class="price">
                    Price: {{price}} <?php echo $this->getCurrency(); ?>
                </div>
                <div class="fyndiq_price">
                    <label>Fyndiq Discount:</label>
                    <input type="text" value="{{fyndiq_price}}" class="fyndiq_dicsount">% <span id="ajaxFired"></span><br />
                    <span class="price_preview">Expected Price: {{expected_price}}</span> <?php echo $this->getCurrency(); ?>
                </div>
            </td>
            <td class="quantities">
                {{quantity}}
            </td>
            <td class="status">
                {{#if fyndiq_exported}}
                <div class="label green">On Fyndiq</div>
                {{else}}
                <div class="label yellow">Not on Fyndiq</div>
                {{/if}}
            </td>
            </tr>
        {{/with}}
        {{/each}}
    </tbody>
    </table>
    {{else}}
    Category is empty.
    {{/if}}
    </div>
    {{> fm-product-list-controls}}
    {{> fm-product-pagination}}
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/jquery.textchange.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/handlebars-v1.1.2.js"></script>

<script type="text/javascript">
    var messages = {};
    <?php foreach($this->getMessages() as $k => $v) {?>
    messages['<?php echo $k; ?>'] = '<?php echo $v; ?>';
    <? } ?>
</script>

<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmGui.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/FmCtrl.js"></script>
<script type="text/javascript" src="<?php echo $this->getFrontendPath(); ?>frontend/js/main.js"></script>


<div class="fm-container">

    <img class="fyndiqlogo" src="<?php echo $this->getFrontendPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">

    <div class="fm-menu">
        <ul>
            <li><a href="<?php echo $this->getAdminPath("fyndiq/admin/index"); ?>" class="active">Export Products</a></li>
            <li><a href="<?php echo $this->getAdminPath("fyndiq/admin/orderlist"); ?>">Imported Orders</a></li>
            <li><a href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Settings</a></li>
        </ul>
        <ul class="right">
            <li><a href="#" onclick="confirmRemoval();">Disconnect Account</a></li>
        </ul>
    </div>

    <div class="fm-left-sidebar">
        <h2>Categories</h2>
        <div class="fm-category-tree-container"></div>
    </div>

    <div class="fm-main-panel">

        <h2>Products</h2>
        <form action="" method="post" class="fm-form products">
            <fieldset>
                <legend>Products</legend>
                <p>By using this form, you can export products from the local webshop into Fyndiq.</p>


                <div class="fm-product-list-container"></div>
            </fieldset>
        </form>
    </div>
</div>
