<?php $skipJS = true; require('common.phtml'); ?>

<div class="fm-container">
    <div class="fm-header">
        <div class="fm-header-wrapper">
            <img class="navbar-brand" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
        </div>
    </div>

    <div class="fm-content-wrapper">
        <div class="fm-panel">
            <div class="fm-panel-header">Setting up your Fyndiq Connection</div>
            <div class="fm-panel-body">
                <p>
                    By authenticating you will create a permanent connection to your Fyndiq merchant account.<br>
                    (You will not have to authenticate again when coming here next time.)
                </p>
                <p>
                    If you see this page again, it means you typed in wrong credentials and need to type in correct token and username.
                </p>
                <a class="fm-button green" type="submit" name="submit_show_settings"
                   href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Go to
                    Settings</a>
            </div>
        </div>
    </div>
</div>
