<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getFrontendPath(); ?>frontend/css/main.css" media="all">

<div class="fm-header-background">
    <div class="fm-header-container">
        <div class="fm-header">
            <img class="fyndiqlogo center" src="<?php echo $this->getSharedPath(); ?>frontend/images/logo.png" alt="Fyndiq logotype">
        </div>
    </div>
</div>
<div class="fm-container">
    <div class="fm-main-panel">
        <div class="fm-subheader center">Setting up your Fyndiq Connection</div>
        <div class="content">
            <p>
                By authenticating you will create a permanent connection to your Fyndiq merchant account.<br>
                (You will not have to authenticate again when coming here next time.)
            </p>
            <p>
                If you see this page again, it means you typed in wrong credentials and need to type in correct token and username.
            </p>
            <a class="fm-button green" type="submit" name="submit_show_settings"
               href="<?php echo $this->getAdminPath("adminhtml/system_config/edit/section/fyndiq"); ?>">Go to
                Settings</a>
        </div>
    </div>
</div>